#!/bin/bash

# --- Configuration (Relative Paths) ---
STEAMCMD_PATH="./steamcmd/steamcmd.sh"
ZIP_PATH="./7zz"
INSTALL_DIR="."
APP_ID="322330"

# Files
OVERRIDES_FILE="./DoNotStarveTogether/config/server/Master/modoverrides.lua"
MOD_SETUP_FILE="./mods/dedicated_server_mods_setup.lua"

# Destination Paths
SRC="./Steam/steamapps/workshop/content/$APP_ID"
MODS_DIR="./mods"
MASTER_UGC="./ugc_mods/server/Master/content/$APP_ID"
CAVES_UGC="./ugc_mods/server/Caves/content/$APP_ID"

# ---------------------------------------------------------
# Phase 1: Clean Up Old Mods
# ---------------------------------------------------------
echo ""
echo "========================================================="
echo "PHASE 1: Cleaning old Legacy mod folders"
echo "========================================================="
# 在处理新模组前，彻底删除已存在的 workshop- 文件夹，防止旧模组残留加载
if [ -d "$MODS_DIR" ]; then
    rm -rf "$MODS_DIR"/workshop-*
    echo "Done: Removed all existing workshop folders from $MODS_DIR"
fi
echo "---------------------------------------------------------"

# ---------------------------------------------------------
# Phase 2: ID Extraction
# ---------------------------------------------------------
echo ""
echo "========================================================="
echo "PHASE 2: Extracting IDs from Master modoverrides"
echo "========================================================="

if [ ! -f "$OVERRIDES_FILE" ]; then
    echo "ERROR: Overrides file not found at $OVERRIDES_FILE"
    exit 1
fi

# 从 modoverrides.lua 中提取所有的 workshop ID
mapfile -t UNIQUE_IDS < <(grep -oE 'workshop-[0-9]+' "$OVERRIDES_FILE" | grep -oE '[0-9]+' | sort -u)

if [ ${#UNIQUE_IDS[@]} -eq 0 ]; then
    echo "ERROR: No workshop IDs found in modoverrides.lua."
    exit 1
fi

echo "Found ${#UNIQUE_IDS[@]} unique mods to process."
echo "---------------------------------------------------------"
echo ""

# ---------------------------------------------------------
# Phase 3: SteamCMD Download
# ---------------------------------------------------------
echo "========================================================="
echo "PHASE 3: Downloading via SteamCMD"
echo "========================================================="

CMD="+force_install_dir $INSTALL_DIR +login anonymous"
for id in "${UNIQUE_IDS[@]}"; do
    CMD="$CMD +workshop_download_item $APP_ID $id"
done
CMD="$CMD +quit"

eval "$STEAMCMD_PATH $CMD"
echo ""
echo "Download phase finished."
echo "---------------------------------------------------------"
echo ""

# ---------------------------------------------------------
# Phase 4: Syncing, Unpacking, and Writing Setup File
# ---------------------------------------------------------
echo "========================================================="
echo "PHASE 4: Syncing, Unpacking, and Setup Creation"
echo "========================================================="

chmod +x "$ZIP_PATH"
mkdir -p "$MODS_DIR" "$MASTER_UGC" "$CAVES_UGC"

# 每次运行都会重新生成 dedicated_server_mods_setup.lua，确保与 overrides 同步
echo "-- Auto-generated by MLSG Scripts" > "$MOD_SETUP_FILE"

for id in "${UNIQUE_IDS[@]}"; do
    mod_path="$SRC/$id"
    
    if [ ! -d "$mod_path" ]; then
        echo "[SKIP]   Mod $id: Folder not found in $SRC (Download failed?)"
        continue
    fi

    # 处理 Legacy Bin 类型 (需要解压)
    if ls "$mod_path"/*.bin >/dev/null 2>&1; then
        echo "[LEGACY] Mod $id -> Unpacking to $MODS_DIR/workshop-$id"
        TARGET_MOD_FOLDER="$MODS_DIR/workshop-$id"

        # 在 setup 文件中注释掉 Legacy 模组，防止重复加载或报错
        echo "-- ServerModSetup(\"$id\")" >> "$MOD_SETUP_FILE"
        
        mkdir -p "$TARGET_MOD_FOLDER"
        bin_file=$(ls "$mod_path"/*.bin | head -n 1)
        
        # 使用 7zz 解压
        "$ZIP_PATH" x "$bin_file" -o"$TARGET_MOD_FOLDER" -y > /dev/null
        
        # 路径修复器：处理 Windows 的反斜杠路径
        (
            cd "$TARGET_MOD_FOLDER"
            for file in *; do
                if [[ "$file" == *"\\"* ]]; then
                    new_path=$(echo "$file" | tr '\\' '/')
                    mkdir -p "$(dirname "$new_path")"
                    mv "$file" "$new_path"
                fi
            done
        )
        
    # 处理 UGC Folder 类型 (直接同步到 shard 目录)
    else
        echo "[UGC]    Mod $id -> Syncing to Shard folders"

        # 将 UGC 模组添加到 dedicated_server_mods_setup.lua 以便服务器识别
        echo "ServerModSetup(\"$id\")" >> "$MOD_SETUP_FILE"
        
        rm -rf "$MASTER_UGC/$id" && mkdir -p "$MASTER_UGC/$id"
        cp -R "$mod_path"/* "$MASTER_UGC/$id/"
        
        rm -rf "$CAVES_UGC/$id" && mkdir -p "$CAVES_UGC/$id"
        cp -R "$mod_path"/* "$CAVES_UGC/$id/"
    fi
done

# --- 添加统计信息到文件底部 ---
echo "" >> "$MOD_SETUP_FILE"
echo "-- Total Mods: ${#UNIQUE_IDS[@]}" >> "$MOD_SETUP_FILE"

# ---------------------------------------------------------
# Phase 5: Final Permissions
# ---------------------------------------------------------
echo ""
echo "========================================================="
echo "PHASE 5: Setting permissions"
echo "========================================================="
chmod -R 777 "$MODS_DIR" "./ugc_mods"

echo ""
echo "========================================================="
echo "SUCCESS: All 5 Phases complete. Server is ready to launch!"
echo "========================================================="
echo ""