#!/bin/bash

# --- Configuration (Relative Paths) ---
STEAMCMD_PATH="./steamcmd/steamcmd.sh"
ZIP_PATH="./7zz"
INSTALL_DIR="."
APP_ID="322330"

# Files
OVERRIDES_FILE="./DoNotStarveTogether/config/server/Master/modoverrides.lua"
MOD_SETUP_FILE="./mods/dedicated_server_mods_setup.lua"

# Destination Paths
SRC="./Steam/steamapps/workshop/content/$APP_ID"
MODS_DIR="./mods"
MASTER_UGC="./ugc_mods/server/Master/content/$APP_ID"
CAVES_UGC="./ugc_mods/server/Caves/content/$APP_ID"

# ---------------------------------------------------------
# Phase 1: ID Extraction
# ---------------------------------------------------------
echo ""
echo "========================================================="
echo "PHASE 1: Extracting IDs from Master modoverrides"
echo "========================================================="

if [ ! -f "$OVERRIDES_FILE" ]; then
    echo "ERROR: Overrides file not found at $OVERRIDES_FILE"
    exit 1
fi

mapfile -t UNIQUE_IDS < <(grep -oE 'workshop-[0-9]+' "$OVERRIDES_FILE" | grep -oE '[0-9]+' | sort -u)

if [ ${#UNIQUE_IDS[@]} -eq 0 ]; then
    echo "ERROR: No workshop IDs found in modoverrides.lua."
    exit 1
fi

echo "Found ${#UNIQUE_IDS[@]} unique mods to process."
echo "---------------------------------------------------------"
echo ""

# ---------------------------------------------------------
# Phase 2: SteamCMD Download
# ---------------------------------------------------------
echo "========================================================="
echo "PHASE 2: Downloading via SteamCMD"
echo "========================================================="

CMD="+force_install_dir $INSTALL_DIR +login anonymous"
for id in "${UNIQUE_IDS[@]}"; do
    CMD="$CMD +workshop_download_item $APP_ID $id"
done
CMD="$CMD +quit"

eval "$STEAMCMD_PATH $CMD"
echo ""
echo "Download phase finished."
echo "---------------------------------------------------------"
echo ""

# ---------------------------------------------------------
# PHASE 3: Syncing, Unpacking, and Writing Setup File
# ---------------------------------------------------------
echo "========================================================="
echo "PHASE 3: Syncing, Unpacking, and Setup Creation"
echo "========================================================="

chmod +x "$ZIP_PATH"
mkdir -p "$MODS_DIR" "$MASTER_UGC" "$CAVES_UGC"

# Clear the dedicated_server_mods_setup.lua file before writing
echo "-- Auto-generated by MLSG Scripts" >> "$MOD_SETUP_FILE"

for id in "${UNIQUE_IDS[@]}"; do
    mod_path="$SRC/$id"
    
    if [ ! -d "$mod_path" ]; then
        echo "[SKIP]   Mod $id: Folder not found in $SRC"
        continue
    fi

    # Handle Legacy Bin
    if ls "$mod_path"/*.bin >/dev/null 2>&1; then
        echo "[LEGACY] Mod $id -> Extracting via 7zz to $MODS_DIR/workshop-$id"
        TARGET_MOD_FOLDER="$MODS_DIR/workshop-$id"

        # Add Legacy Mods as commented out to dedicated_server_mods_setup.lua
        echo "-- ServerModSetup(\"$id\")" >> "$MOD_SETUP_FILE"
        
        rm -rf "$TARGET_MOD_FOLDER"
        mkdir -p "$TARGET_MOD_FOLDER"
        bin_file=$(ls "$mod_path"/*.bin | head -n 1)
        
        "$ZIP_PATH" x "$bin_file" -o"$TARGET_MOD_FOLDER" -y > /dev/null
        
        # Path Fixer for Windows backslashes
        (
            cd "$TARGET_MOD_FOLDER"
            for file in *; do
                if [[ "$file" == *"\\"* ]]; then
                    new_path=$(echo "$file" | tr '\\' '/')
                    mkdir -p "$(dirname "$new_path")"
                    mv "$file" "$new_path"
                fi
            done
        )
        
    # Handle UGC Folder
    else
        echo "[UGC]    Mod $id -> Syncing to Shard folders"

        # Add active UGC Mods to dedicated_server_mods_setup.lua
        echo "ServerModSetup(\"$id\")" >> "$MOD_SETUP_FILE"
        
        rm -rf "$MASTER_UGC/$id" && mkdir -p "$MASTER_UGC/$id"
        cp -R "$mod_path"/* "$MASTER_UGC/$id/"
        
        rm -rf "$CAVES_UGC/$id" && mkdir -p "$CAVES_UGC/$id"
        cp -R "$mod_path"/* "$CAVES_UGC/$id/"
    fi
done

# --- ADDED: Total Mod Count Footer ---
echo "" >> "$MOD_SETUP_FILE"
echo "-- Total Mods: ${#UNIQUE_IDS[@]}" >> "$MOD_SETUP_FILE"

# --- Final Step: Cleanup & Finish ---
echo ""
echo "Setting permissions..."
chmod -R 777 "$MODS_DIR" "./ugc_mods"

echo ""
echo "========================================================="
echo "SUCCESS: Mods aligned and dedicated_server_mods_setup.lua updated!"
echo "========================================================="
echo ""