name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - mkdocs  # Trigger on direct push or merge to mkdocs branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        ref: mkdocs  # Checkout code from mkdocs branch

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
        pip install mkdocs-git-revision-date-localized-plugin
        pip install mkdocs-open-in-new-tab

    - name: Build Project
      run: mkdocs build --verbose

    - name: Setup CNAME
      run: echo 'manual.mr-leaves.com' > ./site/CNAME  # Create CNAME file in ./site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # The directory where MkDocs builds the site, usually './site'
        publish_branch: pages  # Publish to main branch for GitHub Pages
